apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-app
  namespace: default
  labels:
    app: tp2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp2-app
 
  # Stratégie de mise à jour sans interruption
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         # Max 1 pod supplémentaire pendant la mise à jour
      maxUnavailable: 0   # 0 : aucun pod indisponible pendant la mise à jour
 
  template:
    metadata:
      labels:
        app: tp2-app
    spec:
      containers:
        - name: tp2-app
          image: europe-west9-docker.pkg.dev/project-5f56a395-7a91-4564-b9e/tp2-registry/tp2-app:v1
 
          ports:
            - containerPort: 8080
 
          # Ressources allouées au conteneur
          resources:
            requests:
              cpu: "100m"      # 100 millicores = 0.1 vCPU
              memory: "128Mi"
            limits:
              cpu: "500m"      # Limite à 500m (0.5 vCPU)
              memory: "512Mi"
 
          # Variables d'environnement depuis le ConfigMap
          envFrom:
            - configMapRef:
                name: tp2-app-config
 
          # Variables d'environnement depuis le Secret
          env:
            - name: REDIS_HOST
              value: "10.104.57.27"   # IP de l'instance Memorystore (ex: 10.x.x.x)
            - name: REDIS_PORT
              value: "6379"
 
          # Probe de disponibilité (Kubernetes coupe le trafic si elle échoue)
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
 
          # Probe de vie (Kubernetes redémarre le pod si elle échoue)
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20